location             = "westus"
resource_group_name  = "terraform-compute"
vm_hostname          = "myvm"
private_vm_name      = "privateVM"
public_web_vm_name   = "publicWebapp"
vm_os_simple         = "UbuntuServer"
vm_size              = "Standard_D2s_v3"
nb_instances         = 1
admin_username       = "azureuser"
ssh_key              = "~/.ssh/azure_rsa.pub"
nb_public_ip         = 0
public_ip_dns        = [""]
enable_nat_gateway   = true
enable_bastion       = false
enable_public_web_vm = true
admin_source_ip      = null
enable_vpn_gateway   = true
vpn_root_cert_data   = "MIICuDCCAaACCQDxk9bLkJZ7/zANBgkqhkiG9w0BAQsFADAeMRwwGgYDVQQDDBNDbG91ZEZvcmNlVlBOUm9vdENBMB4XDTI2MDMyNzEyNDIwM1oXDTM2MDMyNDEyNDIwM1owHjEcMBoGA1UEAwwTQ2xvdWRGb3JjZVZQTlJvb3RDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALHx57yD1g8nfZM0Wu4Wui1YdjqVUfJZJxWOayFDlseyB87Rv34f1rAL9A5OWEPbSdftidcHpQGeUyO0HwlWNZ9EjZpNt7t7UJfS3AwHwJag9Q5NEjztVj8G/rsxdTOsZcHIw03h+e7zDymQnZ7PhBgXBsv57QsNPVNtH21GY3R6eDn2qUQp9S9vJynevcrWtaR/AP5rxrHtAtTyQixZXii93Yhf8AhVBdCeht29mvcf+vFKsb6SCKeayD0eiHLbgEl6NIcJ4q3s0qgWH8RBPIejjlEHVuZV3fPm5k7ElYgVtZQr7bvf4JRzd6GNlTTERzk2J29O1q0T+2JE2SyBsOkCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAecwoMZgNtrRIJ6nrT1NogbhafVnpI5fOMzPilEQ2oZId/qwcs5YwIq5/Od4sxVtjOhl7i98AzG9ZhVmiqXy0nqOOLPxlsnhkRpzbdoyWP3rwDuGPme5TrAvxSg1VriY+SUPhDuRLhekpfCkQhCRKyQ0Od/Pq8qF4YNUyovzKCp7NPTtUzrFSj2Eyv8LwQvMU2Z7HNwV5ptviCJ8LyZy8CZ4eXFaak4wJafTzCh6tgEViL7c47K9RPsLbEjCXhZnae9bZ6ZWbKaTXSln1ZeEO/cQCfezlc54r7cryqic85OfAkzje0WuPGW4hR1uyysEPBG+EvuAEaAF7d58oFkTalQ=="
